// Code generated by https://github.com/chenxyzl/gsgen; DO NOT EDIT.
// gen_tools version: 1.1.5
// generate time: 2024-06-26 10:48:22
package home_model

import (
	"github.com/chenxyzl/gsgen/gsmodel"
	"go.mongodb.org/mongo-driver/bson"
)

func (s *Base) MarshalBSON() ([]byte, error) {
	var doc = bson.M{"name": s.name}
	return bson.Marshal(doc)
}
func (s *Base) UnmarshalBSON(data []byte) error {
	doc := struct {
		Name string `bson:"name"`
	}{}
	if err := bson.Unmarshal(data, &doc); err != nil {
		return err
	}
	s.SetName(doc.Name)
	return nil
}
func (s *Base) BuildBson(m bson.M, preKey string) {
	dirty := s.GetDirty()
	if dirty == 0 {
		return
	}
	if dirty&(1<<0) != 0 {
		gsmodel.AddSetDirtyM(m, gsmodel.MakeBsonKey("name", preKey), s.name)
	}
	return
}
func (s *Base) CleanDirty() {
	s.DirtyModel.CleanDirty()
}
