// Code generated by https://github.com/chenxyzl/gsgen; DO NOT EDIT.
// gen_tools version: 1.1.1
// generate time: 2024-06-19 12:13:21
package model

import (
	"encoding/json"
	"fmt"
)

func (s *Base) GetName() string {
	return s.name
}
func (s *Base) SetName(v string) {
	s.name = v
	s.UpdateDirty(1 << 0)
}
func (s *Base) String() string {
	doc := struct {
		Name string `bson:"name"`
	}{s.name}
	return fmt.Sprintf("%v", &doc)
}
func (s *Base) MarshalJSON() ([]byte, error) {
	doc := struct {
		Name string `bson:"name"`
	}{s.name}
	return json.Marshal(doc)
}
func (s *Base) UnmarshalJSON(data []byte) error {
	doc := struct {
		Name string `bson:"name"`
	}{}
	if err := json.Unmarshal(data, &doc); err != nil {
		return err
	}
	s.SetName(doc.Name)
	return nil
}
func (s *Base) Clone() (*Base, error) {
	data, err := json.Marshal(s)
	if err != nil {
		return nil, err
	}
	ret := Base{}
	err = json.Unmarshal(data, &ret)
	if err != nil {
		return nil, err
	}
	return &ret, nil
}
